vich_uploader:
    db_driver: orm

    mappings:
        fighter_image:
            uri_prefix: /images/fighter
            upload_destination: '%kernel.project_dir%/public/images/fighter'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
